### ISSUE TITLE
Check for valid data

### ISSUE THREAD

**Issue by torwager** [canlab/RobustToolbox#3]
robust regression : need to check that all in-mask voxels have at least 4 valid subjects.

“That did the trick! It seems that the first voxel in slice 15 had data missing for all but 4 subjects.
I’ve made a new mask with the mask_create_from_image_set.m script.”

**Comment by scottmschafer** [comment]
There's a related issue I'm working on in robust_pooled_weight_core where any voxels missing in one subject are saved as NaNs across the group which leads to errors in identifying statistics. I'll add a check that makes sure at least 4 subjects have data within that voxel before displaying it. If no (or very few) subjects have data in a given voxel, I'm also planning on "removing" it from the saved ROI for nonparam, so it doesn't get displayed as an analyzed voxel.
