### ISSUE TITLE
Read me link is dead

### ISSUE THREAD

**Issue by munoztd0** [canlab/RobustToolbox#5]
Hello,

Thanks for this amazing work but I by any chance you could find back the read me file I would really appreciate

**Comment by RJMullins** [comment]
Same problem here, it only leads to a site that says "this topic does not exist yet."

**Comment by torwager** [comment]
Thanks. The readme link was dated - we've moved to a new university (Dartmouth). I've put a new version up with some updates to the code as well. Get the latest version and give it a try!
